# Generated by Django 5.2.4 on 2025-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("admin", "ADMIN"), ("customer", "CUSTOMER")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
