# Generated by Django 5.2.4 on 2025-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                help_text="Required. Enter a valid email address.",
                max_length=254,
                unique=True,
            ),
        ),
    ]
