# Generated by Django 5.2.4 on 2025-08-05 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_account_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
