services:
  backend:
    build: ./server
    container_name: drf-backend
    ports:
      - "8000:8000"
    env_file:
    - ./server/.env
    depends_on:
      db :
        condition: service_healthy

  frontend:
    build: ./client
    container_name: react-frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:16.10-alpine3.21
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: roman
      POSTGRES_PASSWORD: roman
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: