# Generated by Django 5.2.4 on 2025-09-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_options"),
        ("product", "0002_alter_product_category_delete_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("id",), "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Select the product category",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.category",
            ),
        ),
    ]
