# Generated by Django 5.2.4 on 2025-09-03 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("id",), "verbose_name_plural": "Categories"},
        ),
    ]
